---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)# Load the ape package
library(ape)
library(readxl)
library(tidyr)
library(ggpubr)
```


parameters for plotting

```{r}
my_theme<-theme(axis.text=element_text(size=12),
        axis.title = element_text(size = 14),
        legend.text=element_text(size=10),
        legend.title = element_text(size=12),
        plot.title = element_text(face="bold",size=14,margin=margin(0,0,20,0),hjust = 0.5),
        axis.title.y = element_text(hjust = 0.5),
        axis.title.x = element_text(hjust = 0.5))
```




```{r}
df <- read_excel("04april24_datalab.xlsx", sheet = 3)
df$nematode_count[which(df$nematode_count == ">100")] <- "100"
df$nematode_count <- as.numeric(df$nematode_count)


hist(df$nematode_count)
```


```{r}

df <- df %>%
  mutate(nematode_count_categories = cut(nematode_count, 
                          breaks = c(-Inf, 0, 10, 30, Inf), 
                          labels = c("absence", "low", "moderate", "high"),
                          include.lowest = TRUE)) 

```

```{r}
# Filter out NA values from your data frame
filtered_df <- df %>%
  filter(!is.na(nematode_count_categories))

# Plotting the filtered data
total_counts <- ggplot(filtered_df, aes(x = nematode_count_categories, fill = nematode_count_categories)) +
  geom_bar(show.legend = FALSE) +
  labs(title = "Distribution of Categories",
       x = "Categories",
       y = "Count") +
  scale_fill_manual(values = c("absence" = "gray", "low" = "blue", "moderate" = "green", "high" = "red")) +
  xlab("") +
  theme_classic() +
  my_theme

total_counts

ggsave("output/exploratory/total_counts.jpeg", height = 7, width = 7)

```


# Species sampled per island

```{r}

# Count the number of species per island
species_counts <- filtered_df %>%
  group_by(island) %>%
  summarise(num_species = length(unique(spp)))

# Reorder the levels of the "island" factor based on the number of species
species_counts <- species_counts %>%
  mutate(island = factor(island, levels = island[order(num_species)]))


# Plot the number of species per island
nspp_island <- ggplot(species_counts, aes(x = island, y = num_species)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = num_species), vjust = -0.5, size = 5) +  # Add text labels
  labs(title = "Number of sampled species per island",
       x = "Island",
       y = "Number of Species") +
  theme(axis.text.x = element_text(angle = 45, vjust = c(1, 0))) +  # Adjust angle and vjust
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  theme_classic()+
  my_theme


nspp_island


ggsave("output/exploratory/nspp_island.jpeg", height = 7, width = 8)

```



# Parasitic load per species and island


```{r}

plot_counts_spp_island <- ggplot(df, aes(x = spp, fill = nematode_count_categories)) +
  geom_bar(stat = "count", position = "stack") +  # Use position = "stack" for stacked bar plots
  labs(title = "Nematode Counts per Species and Category",
       x = "Species",
       y = "Nematode Counts") +
  facet_wrap(~ island, scales = "free", strip.position = "top") +
  theme_classic() +
  theme(
    legend.position = "top",
    legend.box = "horizontal",
    legend.spacing.x = unit(0.2, "cm"),
    axis.text.x = element_text(angle = 45, hjust = 1) 
  ) +
 scale_fill_manual(values = c("absence" = "gray", "low" = "blue", "moderate" = "green", "high" = "red"))+
  xlab("")

plot_counts_spp_island

ggsave("output/exploratory/barplots_counts_spp_island_v2.jpeg", height = 9, width = 9)

```



```{r}
unique_pulls <- df %>%
  group_by(spp) %>%
  summarize(num_unique_pulls = n_distinct(id, na.rm = TRUE))


ggplot(unique_pulls, aes(x = num_unique_pulls)) +
  geom_bar(fill = "grey20", color = "black") +
  scale_y_continuous(breaks = seq(0, max(unique_pulls$num_unique_pulls), by = 1)) + 
  labs(title = "Distribution of n locations \nof examined specimens per species",
       x = "N locations in positive pulls",
       y = "Frequency") +
  theme_classic()+
  my_theme


ggsave("output/exploratory/barplots_nlocations_examinations.jpeg", height = 5, width = 9)

```



# compute a mean parasitic load

```{r}

df_load <- df %>%
  group_by(spp) %>%
  summarise(n = n(),
            mean_load = mean(nematode_count, na.rm = TRUE),
            sd_load = sd(nematode_count, na.rm = TRUE)) %>%
  arrange(desc(mean_load))

colnames(df_load) = c("species", "n" ,"mean_load", "sd_load")

df_totals <- data.frame("n" = sum(df_load$n),
           "mean_load" = mean(df_load$mean_load),
           "sd_load" = mean(df_load$sd_load))

df_load <- bind_rows(df_load, df_totals)

df_load$mean_load <- round(df_load$mean_load, 1)
df_load$sd_load <- round(df_load$sd_load, 1)

df_load

#write.csv(df_load, "output/df_load.csv")

```



# Brightness, habitat, island characteristics

```{r}
# brightness
df_kraemer <- read.csv("kraemer2019/kraemer2019_brightness_scores.csv")

# habitat
df_microhab <- read_excel("04april24_datalab.xlsx", sheet = "spp_mynames_features")

#island

df_island <- read_excel("04april24_datalab.xlsx", sheet = "island_characteristics")
```




# shell brightness

```{r}

df_kraemer <- df_kraemer %>% 
  select(spp, brightness)

df_brightness <- df_kraemer %>%
  group_by(spp) %>%
  summarise(
    mean_brightness = mean(brightness, na.rm = TRUE),
    sd_brightness = sd(brightness, na.rm = TRUE)
  )


df_brightness

```




### Load vs brightness (individual data for load)


```{r}
df_combined <- df_load %>%
  left_join(df_brightness, by = "species")

df_combined

```



```{r}
# Compute summary statistics for df_load
df_load_indiv <- df %>%
  group_by(spp) %>%
  summarise(n = n(),
            mean_load = mean(nematode_count, na.rm = TRUE),
            sd_load = sd(nematode_count, na.rm = TRUE)) %>%
  arrange(desc(mean_load))

# Merge df with df_brightness to get mean_brightness and sd_brightness
df_combined <- df %>%
  left_join(df_brightness, by = "spp")

# Merge df_combined with df_load to get mean_load and sd_load for each species
df_combined <- df_combined %>%
  left_join(df_load_indiv, by = "spp")

plot_brighness_load <- ggplot(df_combined, aes(x = mean_brightness, y = nematode_count)) +
  geom_jitter(width = 0.2, alpha = 0.4) + # Jittered points for distribution
  stat_summary(aes(y = mean_load), fun = mean, geom = "point", color = "red", size = 3) + # Mean points
  stat_summary(aes(y = mean_load), fun.data = mean_sdl, fun.args = list(mult = 1), geom = "errorbar", width = 0.2, color = "red") + # Error bars
  geom_smooth(method = "gam", se = FALSE, linetype = "dashed",color = "blue") + # Add tendency line
  labs(x = "Mean shell brightness",
       y = "Nematode count") +
  theme_bw() +
  my_theme

plot_brighness_load

ggsave("figures/brightness_load.png", height = 8, width = 7)
```


```{r}


colnames(df_brightness)[1] <- "species"

# Merge df_load with df_brightness based on species
combined_df <- left_join(df_load, df_brightness, by = "species")

colnames(df_microhab)[1] <- "species"

# Merge combined_df with df_microhab based on additional common columns
combined_df <- left_join(combined_df, df_microhab, by = c("species"))

combined_df
```


```{r}

df <- df %>%
  rename(species = spp)

# Step 1: Add the island name corresponding to each species in combined_df
combined_df <- combined_df %>%
  left_join(df %>%
              distinct(species, island), by = "species")

# Step 2: Merge combined_df with df_island based on the island name
combined_df <- combined_df %>%
  left_join(df_island, by = c("island" = "island"))

# Step 3: Create the new columns "island_age" and "island_area" in combined_df
combined_df <- combined_df %>%
  mutate(island_age = mean_emergence,
         island_area = area)

combined_df <- combined_df[-nrow(combined_df),]

combined_df

```


PLOTS

```{r}
back_transform_sqrt <- function(x) {
  return(x^2)  # Square back the transformed value
}
```


```{r}
# (1) Boxplot of mean_load in function of microhabitat
boxplot_microhabitat <- ggplot(combined_df %>% filter(!is.na(microhabitat)), aes(x = microhabitat, y = mean_load)) +
  geom_boxplot() +
  geom_point(position = position_jitter(width = 0.1), alpha = 0.5) +  # Add points with jitter
  labs(
       x = NULL,
       y = "Mean nematode load") +
  theme_bw() +
  my_theme

# (2) Boxplot of mean_load in function of vegetation zone (excluding NA values)
boxplot_vegetation <- ggplot(combined_df %>% filter(!is.na(vegetation_zone)), aes(x = vegetation_zone, y = mean_load)) +
  geom_boxplot() +
  geom_point(position = position_jitter(width = 0.1), alpha = 0.5) +  # Add points with jitter
  labs(
       x = NULL,
       y = "Mean nematode load") +
  theme_bw() +
  my_theme

# (3) Plot of mean_load in function of island age
plot_island_age <- ggplot(combined_df, aes(x = island_age, y = mean_load)) +
  geom_point() +
  labs(
       x = "Island age",
       y = "Mean nematodes load")+
  theme_bw()+
  my_theme

# (4) Plot of mean_load in function of island size
plot_island_size <- ggplot(combined_df, aes(x = sqrt(island_area), y = mean_load)) +
  geom_point() +
  labs(
       x = expression("Island area ("~km^2~")"),
       y = "Mean nematode load") +
  scale_x_continuous(labels = back_transform_sqrt) +
  theme_bw() +
  my_theme



# Combine the plots using ggarrange
combined_plot <- ggarrange(boxplot_microhabitat, 
                           boxplot_vegetation + ylab(""), 
                           plot_island_age, 
                           plot_island_size + ylab(""),
                           ncol = 2, nrow = 2,
                           labels = LETTERS[1:4])

combined_plot

#ggsave("figures/load_habitat_island.png", height = 9, width = 8)
```


```{r}

# Calculate the mean load for each island
mean_load_by_island <- combined_df %>%
  group_by(island) %>%
  summarize(mean_load = mean(mean_load, na.rm = TRUE))

# Reorder the islands based on the mean load value
ordered_islands <- mean_load_by_island %>%
  arrange(desc(mean_load)) %>%
  pull(island)

# Plot with x-axis categories ordered by mean_load value
plot_island_name <- ggplot(combined_df, aes(x = factor(island, levels = ordered_islands), y = mean_load)) +
  geom_boxplot() +
  geom_point(position = position_jitter(width = 0.2), alpha = 0.5, size = 2) +  # Add points with jitter
  labs(
       x = NULL,
       y = "Mean nematodes load") +
  theme_bw() +
  my_theme +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

plot_island_name

#ggsave("figures/load_islandname.png", height = 7, width = 8)

```



