---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
```


```{r}
my_theme<-theme(axis.text=element_text(size=12),
        axis.title = element_text(size = 14),
        legend.text=element_text(size=10),
        legend.title = element_text(size=12),
        plot.title = element_text(face="bold",size=14,margin=margin(0,0,20,0),hjust = 0.5),
        axis.title.y = element_text(hjust = 0.5),
        axis.title.x = element_text(hjust = 0.5))
```



```{r}
df <- read.csv("sampling.csv", header = TRUE)
df$nematode_count[which(df$nematode_count == ">100")] <- "100"
df$nematode_count <- as.numeric(df$nematode_count)
#df <- df[1:2413,]
hist(df$nematode_count)
```


```{r}

df <- df %>%
  mutate(nematode_count_categories = cut(nematode_count, 
                          breaks = c(-Inf, 0, 10, 30, Inf), 
                          labels = c("absence", "low", "moderate", "high"),
                          include.lowest = TRUE)) 

```

```{r}
# Filter out NA values from your data frame
filtered_df <- df %>%
  filter(!is.na(nematode_count_categories))

# Plotting the filtered data
total_counts <- ggplot(filtered_df, aes(x = nematode_count_categories, fill = nematode_count_categories)) +
  geom_bar(show.legend = FALSE) +
  labs(title = "Distribution of Categories",
       x = "Categories",
       y = "Count") +
  scale_fill_manual(values = c("absence" = "gray", "low" = "blue", "moderate" = "green", "high" = "red")) +
  xlab("") +
  theme_classic() +
  my_theme

total_counts

ggsave("total_counts.jpeg", height = 7, width = 7)

```


# Species sampled per island

```{r}

# Assuming your data frame is named 'df' and the columns are named 'spp', 'island', and 'nematode_count'
# Count the number of species per island
species_counts <- filtered_df %>%
  group_by(island) %>%
  summarise(num_species = length(unique(spp)))

# Reorder the levels of the "island" factor based on the number of species
species_counts <- species_counts %>%
  mutate(island = factor(island, levels = island[order(num_species)]))


# Plot the number of species per island
nspp_island <- ggplot(species_counts, aes(x = island, y = num_species)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = num_species), vjust = -0.5, size = 5) +  # Add text labels
  labs(title = "Number of Species per Island",
       x = "Island",
       y = "Number of Species") +
  theme(axis.text.x = element_text(angle = 45, vjust = c(1, 0))) +  # Adjust angle and vjust
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  theme_classic()+
  my_theme


nspp_island


ggsave("nspp_island.jpeg", height = 7, width = 8)

```



# Parasitic load per species and island


```{r}

plot_counts_spp_island <- ggplot(df, aes(x = spp, fill = nematode_count_categories)) +
  geom_bar(stat = "count", position = "stack") +  # Use position = "stack" for stacked bar plots
  labs(title = "Nematode Counts per Species and Category",
       x = "Species",
       y = "Nematode Counts") +
  facet_wrap(~ island, scales = "free", strip.position = "top") +
  theme_classic() +
  theme(
    legend.position = "top",
    legend.box = "horizontal",
    legend.spacing.x = unit(0.2, "cm"),
    axis.text.x = element_text(angle = 45, hjust = 1) 
  ) +
 scale_fill_manual(values = c("absence" = "gray", "low" = "blue", "moderate" = "green", "high" = "red"))+
  xlab("")

plot_counts_spp_island

ggsave("barplots_counts_spp_island_v2.jpeg", height = 7, width = 15)

```


# compute a mean parasitic load

```{r}

df_load <- df %>%
  group_by(spp) %>%
  summarise(mean_load = mean(nematode_count, na.rm = TRUE)) %>%
  arrange(desc(mean_load))

colnames(df_load) = c("sp", "mean_load")

df_load

```


# shell brightness

```{r}
df_brightness <- read.csv("kraemer2019_brightness_scores.csv")


df_brightness <- df_brightness[,c("sp", "brightness")]

# compute men brightness per spp

df_brightness <- df_brightness %>% 
  group_by(sp) %>% 
  summarise(mean_brightness = mean(brightness, na.rm = TRUE),
            sd_brightness = sd(brightness, na.rm = TRUE))

df_brightness <- df_brightness %>%
  filter(!(sp %in% c("AL sp.2", 
                     "AL sp.3",
                     "cf perspectivus FL",
                     "cf. nesioticus 'little'",
                     "cf. nesioticus SC E",
                     "cf. nesioticus SC W",
                     "unknownblack")))

```


```{r}
merged_df <- inner_join(df_load, df_brightness, by = "sp")

cor(merged_df$mean_brightness, merged_df$mean_load)


```






