---
title: "R Notebook"
---


```{r}
library(readxl)
library(raster)
library(sf)
library(ggplot2)
library(ggspatial)
library(dplyr)
```



```{r}
data_coord <- read_excel(here::here("a_data/04april24_datalab.xlsx"), sheet = 3)

data_coord <-  data_coord |> 
  distinct(spp, id, .keep_all = TRUE)
```





```{r}
library(sf)

# directory containing the .asc files
asc_files_directory <- here::here("../maps/elevation_finer")

# List all .asc files in the directory
asc_files <- list.files(path = asc_files_directory, pattern = "\\.asc$", full.names = TRUE)

# Load the .asc files into a list of raster objects
rasters <- lapply(asc_files, raster)

# Combine the raster objects into a single raster
combined_raster <- do.call(merge, rasters)


utm_crs_string <- "+proj=utm +zone=15 +datum=WGS84 +units=m +no_defs"


# Define the CRS for the raster if not already defined
crs(combined_raster) <- CRS(utm_crs_string)


# Convert raster to data frame
raster_df <- as.data.frame(combined_raster, xy = TRUE)
colnames(raster_df) <- c("x", "y", "elevation")


# Remove rows with missing coordinate values
data_coord <- data_coord %>% 
  filter(!is.na(latitude) & !is.na(longitude))


# Convert data_coord_sf to a spatial object with coordinates
data_coord_sf <- st_as_sf(data_coord, coords = c("longitude", "latitude"), crs = 4326) %>%
  st_transform(crs = utm_crs_string)

# Convert sf object to data frame with coordinates
data_coord_df <- data_coord_sf %>%
  st_coordinates() %>%
  as.data.frame() %>%
  cbind(data_coord_sf)


# Plot the raster and the points
ggplot() +
  geom_raster(data = raster_df, aes(x = x, y = y-10000000, fill = elevation)) +
  geom_point(data = data_coord_df, aes(x = X, y = Y), color = "red", size = 2) +
  scale_fill_viridis_c() +
  coord_equal() +
  labs(fill = "Elevation") +
  theme_minimal()
```

