---
title: "Data exploratory"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)# Load the ape package
library(ape)
library(readxl)
library(tidyr)
library(ggpubr)
library(ade4)
library(vegan)

library(brms)
library(dplyr)
```


parameters for plotting

```{r}
my_theme<-theme(axis.text=element_text(size=12),
        axis.title = element_text(size = 14),
        legend.text=element_text(size=10),
        legend.title = element_text(size=12),
        plot.title = element_text(face="bold",size=14,margin=margin(0,0,20,0),hjust = 0.5),
        axis.title.y = element_text(hjust = 0.5),
        axis.title.x = element_text(hjust = 0.5))
```




```{r}
df <- read_excel("04april24_datalab.xlsx", sheet = 3)
df$nematode_count[which(df$nematode_count == ">100")] <- "100"
df$nematode_count <- as.numeric(df$nematode_count)


hist(df$nematode_count)
```


```{r}

df <- df %>%
  mutate(nematode_count_categories = cut(nematode_count, 
                          breaks = c(-Inf, 0, 10, 30, Inf), 
                          labels = c("absence", "low", "moderate", "high"),
                          include.lowest = TRUE)) 

```

```{r}
# Filter out NA values from your data frame
filtered_df <- df %>%
  filter(!is.na(nematode_count_categories))

# Plotting the filtered data
total_counts <- ggplot(filtered_df, aes(x = nematode_count_categories, fill = nematode_count_categories)) +
  geom_bar(show.legend = FALSE) +
  labs(title = "Distribution of Categories",
       x = "Categories",
       y = "Count") +
  scale_fill_manual(values = c("absence" = "gray", "low" = "blue", "moderate" = "green", "high" = "red")) +
  xlab("") +
  theme_classic() +
  my_theme

total_counts

ggsave("output/exploratory/total_counts.jpeg", height = 7, width = 7)

```


# Species sampled per island

```{r}

# Count the number of species per island
species_counts <- filtered_df %>%
  group_by(island) %>%
  summarise(num_species = length(unique(spp)))

# Reorder the levels of the "island" factor based on the number of species
species_counts <- species_counts %>%
  mutate(island = factor(island, levels = island[order(num_species)]))


# Plot the number of species per island
nspp_island <- ggplot(species_counts, aes(x = island, y = num_species)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = num_species), vjust = -0.5, size = 5) +  # Add text labels
  labs(title = "Number of sampled species per island",
       x = "Island",
       y = "Number of Species") +
  theme(axis.text.x = element_text(angle = 45, vjust = c(1, 0))) +  # Adjust angle and vjust
  scale_x_discrete(guide = guide_axis(n.dodge=2))+
  theme_classic()+
  my_theme


nspp_island


ggsave("output/exploratory/nspp_island.jpeg", height = 7, width = 8)

```



# Parasitic load per species and island


```{r}

plot_counts_spp_island <- ggplot(df, aes(x = spp, fill = nematode_count_categories)) +
  geom_bar(stat = "count", position = "stack") +  # Use position = "stack" for stacked bar plots
  labs(title = "Nematode Counts per Species and Category",
       x = "Species",
       y = "Nematode Counts") +
  facet_wrap(~ island, scales = "free", strip.position = "top") +
  theme_classic() +
  theme(
    legend.position = "top",
    legend.box = "horizontal",
    legend.spacing.x = unit(0.2, "cm"),
    axis.text.x = element_text(angle = 45, hjust = 1) 
  ) +
 scale_fill_manual(values = c("absence" = "gray", "low" = "blue", "moderate" = "green", "high" = "red"))+
  xlab("")

plot_counts_spp_island

ggsave("output/exploratory/barplots_counts_spp_island_v2.jpeg", height = 9, width = 9)

```



```{r}
unique_pulls <- df %>%
  group_by(spp) %>%
  summarize(num_unique_pulls = n_distinct(id, na.rm = TRUE))


ggplot(unique_pulls, aes(x = num_unique_pulls)) +
  geom_bar(fill = "grey20", color = "black") +
  scale_y_continuous(breaks = seq(0, max(unique_pulls$num_unique_pulls), by = 1)) + 
  labs(title = "Distribution of n locations \nof examined specimens per species",
       x = "N locations in positive pulls",
       y = "Frequency") +
  theme_classic()+
  my_theme


ggsave("output/exploratory/barplots_nlocations_examinations.jpeg", height = 5, width = 9)

```



# compute a mean parasitic load

```{r}

df_load <- df %>%
  group_by(spp) %>%
  summarise(n = n(),
            mean_load = mean(nematode_count, na.rm = TRUE),
            sd_load = sd(nematode_count, na.rm = TRUE)) %>%
  arrange(desc(mean_load))

colnames(df_load) = c("species", "n" ,"mean_load", "sd_load")

df_totals <- data.frame("n" = sum(df_load$n),
           "mean_load" = mean(df_load$mean_load),
           "sd_load" = mean(df_load$sd_load))

df_load <- bind_rows(df_load, df_totals)

df_load$mean_load <- round(df_load$mean_load, 1)
df_load$sd_load <- round(df_load$sd_load, 1)

df_load

#write.csv(df_load, "output/df_load.csv")

```


