---
title: "R Notebook"
editor_options: 
  chunk_output_type: console
---

## load and combine data

```{r}
library(tidyverse)
library(readxl)
library(naniar)
# library(ape)
# library(ggpubr)
# library(ade4)
library(vegan)
library(stringr)
library(brms)
library(cmdstanr)
library(bayesplot)
library(tidybayes)
library(posterior)
```

# load csv with species names for checks

```{r}
species_names_df <- read_csv(here::here("species_names_checks.csv"))
species_names_df <- species_names_df %>% 
  rename(species = annotated_name)

species_names_df
```


## Load dataset

```{r}
df_load_raw <- read_excel(path = here::here("a_data/19july24_datalab.xlsx"), 
                          sheet = 3,
                          col_types = c("text", "text", "text", "text", "text", 
                                       "text", "numeric", "numeric", "text", 
                                       "text", "text"))

df_load_raw$nematode_count <- df_load_raw$nematode_count |> 
  readr::parse_number()

df_load <- df_load_raw %>% 
  select(id, spp, nematode_count, island) %>% 
  rename(species = spp)

# correct species names
df_load <- df_load %>%
  left_join(species_names_df, by = "species")

df_load
```

## island info

```{r}
df_island <- read_excel(path = here::here("a_data/19july24_datalab.xlsx"),
                        sheet = "island_characteristics")

# Rename the column "mean_emergence" to "island_age" in df_island
df_island <- df_island %>% rename(island_age = mean_emergence,
                                  island_area = area)

df_island

```



# brightness data

```{r}

df_kraemer <- read_csv(here::here("a_data/kraemer2019_brightness_scores.csv"))
df_kraemer <- df_kraemer %>% 
  select(location, spp, brightness, microhab) %>% 
  rename(id = location,
         species = spp)


# correct species names
df_kraemer_corrected <- df_kraemer %>%
  left_join(species_names_df, by = "species")

df_kraemer_corrected

```




# habitat data



### habitat data from RAD sequences database

```{r}
df_rad <- read_excel(here::here("a_data/GPS RAD snails.xlsx"))
df_rad <- df_rad %>% 
  select(Sample, Taxon, 
         habitat = Microhabitat, 
         vegetation = `Vegetation Zone`)%>% 
  rename(species = Taxon) %>% 
  glimpse() 


# correct species names
df_rad_corrected <- df_rad %>%
  left_join(species_names_df, by = "species")


# Semi-Arboreal is considered arboreal
df_rad_relevel_hab <- df_rad_corrected %>%
  mutate(habitat = str_to_lower(habitat)) %>% 
  mutate(habitat = str_replace(habitat, "semi-arboreal", "arboreal"))

df_rad_relevel_hab |> 
  count(habitat)

## we have a SECOND source for habitat data
df_rad_hab_filtered <- df_rad_relevel_hab %>%
  filter(habitat %in% c("arboreal", "terrestrial")) |> 
  select(species, microhab = habitat)

###############################



# select columns and combine with habitat data from Kraemer 2019 database
df_hab_combo_agg <- df_kraemer_corrected |>
  select(species_name, microhab) |> 
  bind_rows(df_rad_hab_filtered)|> 
  count(species_name, microhab) |> 
  pivot_wider(values_from = n, names_from = microhab, values_fill = 0) |> 
  mutate(total_hab = terrestrial + arboreal)

# correct species names
df_hab_combo_agg

```


```{r}
# repeat and relevel vegetation
df_rad_veg_agg <- df_rad_relevel_hab %>% 
  mutate(vegetation = str_to_lower(vegetation)) %>% 
  ## filter for only legal values -- others are typos
  filter(vegetation %in% c("humid", "arid")) |> 
  count(species_name, vegetation) |> 
  pivot_wider(values_from = n, names_from = vegetation, values_fill = 0) |> 
  mutate(total_veg = humid + arid) |> 
  rename(species = species_name)


# correct species names
df_rad_veg_agg <- df_rad_veg_agg %>%
  left_join(species_names_df, by = "species")

df_rad_veg_agg

```



Datasets, with same species_codes:

```{r}

# load

df_load |> 
  select(species_name, nematode_count)

# brightness

df_brightness <- df_kraemer_corrected |> 
  select(species_name, brightness)

# habitat

n_double_spp <- df_hab_combo_agg |> 
  add_count(species_name) |> 
  filter(n>1) |> 
  nrow()

stopifnot(n_double_spp == 0)
if (n_double_spp > 0) stop("damn there's an extra species")

# vegetation

n_double_spp <- df_rad_veg_agg |> 
  add_count(species_name) |> 
  filter(n>1) |> 
  nrow()

```


```{r}
## drop all NA species

```

