---
title: "R Notebook"
---

```{r}
library(dplyr)
library(ggplot2)# Load the ape package
library(ape)
library(readxl)
library(tidyr)
library(ggpubr)
library(ade4)
library(vegan)
library(stringr)
library(brms)
library(dplyr)
library(tidyverse)
library(cmdstanr)
library(bayesplot)
library(tidybayes)
library(posterior)
```


parameters for plotting

```{r}
my_theme<-theme(axis.text=element_text(size=12),
        axis.title = element_text(size = 14),
        legend.text=element_text(size=10),
        legend.title = element_text(size=12),
        plot.title = element_text(face="bold",size=14,margin=margin(0,0,20,0),hjust = 0.5),
        axis.title.y = element_text(hjust = 0.5),
        axis.title.x = element_text(hjust = 0.5))
```


# df load

```{r}
df_load <- read_excel("../a_data/04april24_datalab.xlsx", sheet = 3)
df_load$nematode_count[which(df_load$nematode_count == ">100")] <- "100"
df_load$nematode_count <- as.numeric(df_load$nematode_count)

df_load <- df_load %>% 
  select(id, spp, nematode_count) %>% 
  rename(species = spp)

df_load
```


# vegetation zone data


### vegetation zone data from RAD sequences database

```{r}
df_rad <- read_excel("../a_data/GPS RAD snails.xlsx")

# Standardize the names to lowercase
df_rad <- df_rad %>%
  mutate(`Vegetation Zone` = tolower(`Vegetation Zone`))

# Filter out rows with unwanted values in the Vegetation Zone column
df_rad <- df_rad %>%
  filter(`Vegetation Zone` %in% c("humid", "arid"))

# Rename the column
df_veg <- df_rad %>%
  rename(vegetation_zone = `Vegetation Zone`)
  
```

Names checks

```{r}
#df_veg[which(df_veg$Taxon == "albermarlensis"),] <- "albemarlensis"
df_veg[which(df_veg$Taxon == "cf. albemarlensis"),"Taxon"] <- "albemarlensis"

#df_veg[which(df_veg$Taxon == "ustulatus pallescens"),] <- "ustulatus"
#df_veg[which(df_veg$Taxon == "ustulatus phlegonis"),] <- "ustulatus"
#df_veg[which(df_veg$Taxon == "ustulatus mahogany"),] <- "ustulatus"

df_veg[which(df_veg$Taxon == "invalidus 1"),"Taxon"] <- "invalidus"
df_veg[which(df_veg$Taxon == "invalidus 2"),"Taxon"] <- "invalidus"

df_veg[which(df_veg$Taxon == "sculpturatus 1"),"Taxon"] <- "sculpturatus"
df_veg[which(df_veg$Taxon == "sculpturatus 2"),"Taxon"] <- "sculpturatus"
df_veg[which(df_veg$Taxon == "sculpturatus 3"),"Taxon"] <- "sculpturatus"

df_veg[which(df_veg$Taxon == "wolfi 1"),"Taxon"] <- "wolfi"
df_veg[which(df_veg$Taxon == "wolfi 2"),"Taxon"] <- "wolfi"
df_veg[which(df_veg$Taxon == "wolfi 3"),"Taxon"] <- "wolfi"

df_veg[which(df_veg$Taxon == "cf. perspectivus"),"Taxon"] <- "perspectivus"
df_veg[which(df_veg$Taxon == "perspectivus 1"),"Taxon"] <- "perspectivus"
df_veg[which(df_veg$Taxon == "perspectivus 2"),"Taxon"] <- "perspectivus"

df_veg[which(df_veg$Taxon == "cf. amastroides"),"Taxon"] <- "amastroides"

df_veg[which(df_veg$Taxon == "canaliferus 1"),"Taxon"] <- "canaliferus"
df_veg[which(df_veg$Taxon == "canaliferus 2"),"Taxon"] <- "canaliferus"

df_veg[which(df_veg$Taxon == "simrothi 1"),"Taxon"] <- "simrothi"
df_veg[which(df_veg$Taxon == "simrothi 2"),"Taxon"] <- "simrothi"

df_veg[which(df_veg$Taxon == "cf. tortuganus"),"Taxon"] <- "tortuganus"

df_veg[which(df_veg$Taxon == "cf. nux"),"Taxon"] <- "nux"


```

Only keep species with assessed load:

```{r}

# Filter df_merged to only include species that appear in df_load
df_veg <- df_veg %>%
  rename(species = Taxon) %>% 
  semi_join(df_load, by = "species")

df_veg
```


### Create common species code to make sure species names coincide

```{r}

# Combine unique species from both dataframes
unique_species <- unique(c(unique(df_load$species), unique(df_veg$species)))

# Create a dictionary of species to letters
species_to_number <- setNames(1:length(unique_species), unique_species)

# Add the letter codes to df_load and df_habitat
df_load$species_code <- species_to_number[df_load$species]
df_veg$species_code <- species_to_number[df_veg$species]

# View the updated dataframes
df_load
df_veg

```


Prepare data

```{r}
# Convert habitat to integer: 0 for terrestrial, 1 for arboreal
df_veg$veg_code <- ifelse(df_veg$vegetation_zone == "humid", 0, 1)

data_list <- list(
  N_nem = nrow(df_load),
  N_veg = nrow(df_veg),
  N_sp_nem = length(unique(df_load$species)),
  load = df_load$nematode_count,
  vegetation = df_veg$veg_code,
  species_i = df_load$species_code,
  species_v = df_veg$species_code
)

```


Model

```{r}

# Fit the model using cmdstanr
stan_load_brightness <- cmdstan_model(
  stan_file = "../c_codeStan/vegetation.stan", 
  pedantic = TRUE
)

fit <- stan_load_brightness$sample(
  data = data_list,
  seed = 123,             
  chains = 4,               
  parallel_chains = 4,    
  iter_warmup = 1000,       
  iter_sampling = 2000   
)

```


## All posterior pars

```{r}
# Extract the posterior samples
posterior_samples <- fit$draws()

# Convert to a data frame for easier handling
posterior_df <- as_draws_df(posterior_samples)

# Rename mu_bright parameters for easier handling
posterior_df <- posterior_df %>%
  rename_with(~ gsub("\\[|\\]", "", .), starts_with("vegetation_prob")) %>%
  rename_with(~ gsub("\\.", "_", .), starts_with("vegetation_prob"))

# Extract the names of the parameters of interest
mu_hab_names <- grep("^vegetation_prob", names(posterior_df), value = TRUE)
#sigma_bright_names <- grep("^sigma_habitat", names(posterior_df), value = TRUE)

parameter_names <- c("intercept", "slope_vegetation", mu_hab_names)
```


```{r}
# Plot posterior distributions of the parameters
mcmc_areas(
  posterior_df,
  pars = parameter_names,
  prob = 0.8  # 80% intervals
)



```


```{r}
fit$draws(variables = c("intercept", "slope_vegetation")) |>
  posterior::summarise_draws("mean", "sd", ~quantile(.x, probs = c(0.05, 0.95)), "rhat") #|>
  #flextable::flextable()
```


### Plot for predicted values


```{r}

# Extract the predicted values from the Stan fit object
predicted_vegetation <- as_draws_matrix(fit$draws("predicted_vegetation"))
predicted_load <- as_draws_matrix(fit$draws("predicted_load"))

# Posterior predictive check for nematode load
ppc_load <- ppc_dens_overlay(y = df_load$nematode_count, yrep = predicted_load) +
  scale_color_manual(name = "Legend",
                     values = c("y" = "black", "yrep" = "blue"),
                     labels = c("Observed load", "Predicted load")) +
  scale_fill_manual(name = "Legend",
                    values = c("y" = "black", "yrep" = "blue"),
                    labels = c("Observed load", "Predicted load"))+
  my_theme

# Posterior predictive check for vegetation (categorical)
observed_vegetation <- as.numeric(df_veg$veg_code)  # Convert to numeric if needed
ppc_vegetation <- ppc_bars(y = observed_vegetation, yrep = predicted_vegetation) +
  scale_color_manual(name = "Legend",
                     values = c("y" = "black", "yrep" = "coral"),
                     labels = c("Observed vegetation", "Predicted vegetation")) +
  scale_fill_manual(name = "Legend",
                    values = c("y" = "black", "yrep" = "coral"),
                    labels = c("Observed vegetation", "Predicted vegetation"))+
  my_theme

# Combine the plots
ppc_plots_load_veg <- ggarrange(
  ppc_load,
  ppc_vegetation,
  labels = LETTERS[1:2],
  ncol = 1,
  nrow = 2
)

ppc_plots_load_veg

ggsave("../d_output/figures/predictions/ppc_load_veg_neg.png", height = 10, width = 10)


```