---
title: "Phylogenetic signal of nematode encapsulations"
---


```{r}
library(phytools)
library(tidyverse)
```


Load data

```{r}

# tree file
tree <- read.tree("a_data/phylogeny_2022/22Nov_Naesiotus.nwk")

tree<- as.phylo(tree)


# codes for the tip names
df_rads <- read_excel("a_data/GPS RAD snails.xlsx")

# load
df_load <- read_excel("a_data/04april24_datalab.xlsx", sheet = 3)
df_load$nematode_count[which(df_load$nematode_count == ">100")] <- "100"
df_load$nematode_count <- as.numeric(df_load$nematode_count)

plot(tree)
```


Compute mean and se load per species

```{r}
df_meanload <- df_load %>%
  group_by(spp) %>%
  summarise(n = n(),
            mean_load = mean(nematode_count, na.rm = TRUE),
            se_load = sd(nematode_count, na.rm = TRUE)/sqrt(length(nematode_count)), 
            sd_load = sd(nematode_count, na.rm = TRUE)) %>%
  arrange(desc(mean_load)) %>% 
  rename(
    species = spp
  )

df_meanload
```



```{r}
meanload<-setNames(df_meanload$mean_load, df_meanload$species)
s.error<-setNames(df_meanload$se_load, df_meanload$species)
```



Correct names in the RAD database 

```{r}
# Names checks

#df_rads[which(df_rads$Taxon == "albermarlensis"),] <- "albemarlensis"
df_rads[which(df_rads$Taxon == "cf. albemarlensis"),"Taxon"] <- "albemarlensis"

#df_rads[which(df_rads$Taxon == "ustulatus pallescens"),] <- "ustulatus"
#df_rads[which(df_rads$Taxon == "ustulatus phlegonis"),] <- "ustulatus"
#df_rads[which(df_rads$Taxon == "ustulatus mahogany"),] <- "ustulatus"

df_rads[which(df_rads$Taxon == "invalidus 1"),"Taxon"] <- "invalidus"
df_rads[which(df_rads$Taxon == "invalidus 2"),"Taxon"] <- "invalidus"

df_rads[which(df_rads$Taxon == "sculpturatus 1"),"Taxon"] <- "sculpturatus"
df_rads[which(df_rads$Taxon == "sculpturatus 2"),"Taxon"] <- "sculpturatus"
df_rads[which(df_rads$Taxon == "sculpturatus 3"),"Taxon"] <- "sculpturatus"

df_rads[which(df_rads$Taxon == "wolfi 1"),"Taxon"] <- "wolfi"
df_rads[which(df_rads$Taxon == "wolfi 2"),"Taxon"] <- "wolfi"
df_rads[which(df_rads$Taxon == "wolfi 3"),"Taxon"] <- "wolfi"

df_rads[which(df_rads$Taxon == "cf. perspectivus"),"Taxon"] <- "perspectivus"
df_rads[which(df_rads$Taxon == "perspectivus 1"),"Taxon"] <- "perspectivus"
df_rads[which(df_rads$Taxon == "perspectivus 2"),"Taxon"] <- "perspectivus"

df_rads[which(df_rads$Taxon == "cf. amastroides"),"Taxon"] <- "amastroides"

df_rads[which(df_rads$Taxon == "canaliferus 1"),"Taxon"] <- "canaliferus"
df_rads[which(df_rads$Taxon == "canaliferus 2"),"Taxon"] <- "canaliferus"

df_rads[which(df_rads$Taxon == "simrothi 1"),"Taxon"] <- "simrothi"
df_rads[which(df_rads$Taxon == "simrothi 2"),"Taxon"] <- "simrothi"

df_rads[which(df_rads$Taxon == "cf. tortuganus"),"Taxon"] <- "tortuganus"

df_rads[which(df_rads$Taxon == "cf. nux"),"Taxon"] <- "nux"

```



```{r}
# Create a mapping between Sample and Taxon
sample_to_taxon <- setNames(df_rads$Taxon, df_rads$Sample)

```


```{r}
# Replace tip labels in the tree with corresponding taxa
tree$tip.label <- sample_to_taxon[tree$tip.label]

plot(tree)
```


Prune tree, discarting those species not assessed for load

```{r}
pruned.tree<-drop.tip(tree, setdiff(tree$tip.label, df_meanload$species))

plot(pruned.tree)
```

Also discard those species in load that are not present in the tree

```{r}
# Filter data to include only species present in the phylogenetic tree
tree_species <- pruned.tree$tip.label
meanload_filtered <- meanload[names(meanload) %in% tree_species]
s.error_filtered <- s.error[names(s.error) %in% tree_species]

# Verify data alignment
match_indices <- match(tree_species, names(meanload_filtered))
meanload_filtered <- meanload_filtered[match_indices]
s.error_filtered <- s.error_filtered[match_indices]
```




# Blomberg's K

```{r}
K_nemaload <- phylosig(pruned.tree, meanload_filtered, method = 'K', test = TRUE, se = s.error_filtered)
K_nemaload
plot.phylosig(K_nemaload)

```


# Lambda

```{r}

lambda_nemaload <- phylosig(pruned.tree, meanload_filtered, method = 'lambda', test = TRUE, se = s.error_filtered) 
lambda_nemaload <- phylosig(pruned.tree, meanload_filtered, method = 'lambda', test = TRUE) 
lambda_nemaload
plot.phylosig(lambda_nemaload)

```




